name: metronomo_definitivo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  torch_controller: ^2.0.1
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  vibration: ^1.9.0
  google_fonts: ^6.2.0
  fluttertoast: ^8.2.5
  provider: ^6.1.2
  wear:
    path: C:/Flutter Packages/flutter_wear_plugin-master
  watch_connectivity: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: BellotaText
      fonts:
        - asset: fonts/BellotaText-Regular.ttf
        - asset: fonts/BellotaText-Italic.ttf
        - asset: fonts/BellotaText-Bold.ttf
        - asset: fonts/BellotaText-BoldItalic.ttf
        - asset: fonts/BellotaText-Light.ttf
        - asset: fonts/BellotaText-LightItalic.ttf
  assets:
    - assets\clique.wav
    - assets\tick.wav
    - assets\music_genres.json
  uses-material-design: true
